spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messagerie
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jms:
    broker-url: tcp://localhost:61616
ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(1414)
    user: admin
    password: passw0rd
    queue: DEV.QUEUE.1

server:
  port: 8080
